server:
  port: 8080
  address: 0.0.0.0
spring:
#  profiles:
#    active: @profilesActive@
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
    username: root
    password: '%Zheng7219212'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  web:
    resources:
      static-locations:
        'classpath:/templates/,classpath:/static/,file:/usr/share/nginx/static/'
  servlet:
    multipart:
      enabled: true
      location: '/usr/share/nginx/static/'
      max-file-size: 200000MB
      max-request-size: 200000MB
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 邮件发送方
  mail:
    host: smtp.exmail.qq.com
    port: 587
    username: 3942607275@qq.com
    password: "di7219212"
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail-smtp-host: smtp.exmail.qq.com
      mail-smtp-auth: true
      mail-smtp-ssl-enable: true
      mail-smtp-socketFactory-class: com.sun.mail.util.MailSSLSocketFactory
      mail-smtp-socketFactory-port: 587
      mail-smtp-socketFactory-fallback: false
      mail-transport-protocol: smtp

flowable:
  database-schema-update: true
  async-executor-activate: false

file:
  base-directory: /usr/share/nginx/static/files  # Linux目录路径
  allowed-directories: /public,/discuz  # 允许访问的目录列表（逗号分隔）

# 邮件接收方
mail:
  to:  3942607275@qq.com
  replyTo: 572233016@qq.com
  #模板位置 templates/email.html
  templatePath: email
  subject: "农村金融开发环境异常警告"

#mybatis-plus配置 开发、测试环境打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/*Mapper.xml
#  typeAliasesPackage: com.school.information.**.entity